### ISSUE TITLE
Markbot doesn't like blue?

### ISSUE THREAD

**Issue by drew0036** [drew0036/accessibility-fixer-upper#1]
![Screen Shot 2020-04-16 at 3 28 59 PM](https://user-images.githubusercontent.com/55107709/79503522-4b9a1a80-7fff-11ea-844f-6661335fead8.png)
 
Hey @muxlowc, 

I'm so close but it does not like my colour contrast on my read more links for some reason. Can you please take a look? 

Thank you!

**Comment by muxlowc** [comment]
@drew0036 

1) remove these from your css:

a:focus {
  color: #f00;
  outline: 3px solid #000;
  text-decoration: underline;
}

.more:focus {
  color: #00f;
  outline: 3px solid #fff;
  text-decoration: underline;
}

2) add: 

.more {
  color: #113c00;
}

So links by default are underlined and have a focus, so you didn't need to add them

**Comment by drew0036** [comment]
Got it! Thank you! You're the best!
